name: Build, Test & Deploy Flutter Web

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'web/**'
      - 'assets/**'
      - 'pubspec.yaml'

jobs:
  build:
    name: Setup Flutter & Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web
          retention-days: 7
          if-no-files-found: error


      # 😞Don't ask me why 'curl' is the only way to upload build to this host...
      - name: Install GNU Parallel
        run: sudo apt-get install -y parallel

      - name: Upload Archive to FTP and Install
        run: |
          echo "Finding all files in build directory..."
          find build/web -type f > files.txt
          echo "Uploading files in parallel..."
          cat files.txt | parallel -j4 "curl --ftp-create-dirs --ftp-pasv -T {} --user '$FTP_USER:$FTP_PASSWORD' 'ftp://$FTP_HOST/$FTP_PATH/{= s#build/web/## =}'"
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PATH: ${{ secrets.FTP_PATH }}
